// <auto-generated />
using EmployeeManagement.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("EmployeeManagement.Server.Data.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address1 = "123 Main St",
                            Address2 = "Apt 4B",
                            City = "Springfield",
                            EmployeeId = 1,
                            State = "IL",
                            Zip = "62701"
                        },
                        new
                        {
                            Id = 2,
                            Address1 = "456 Oak Ave",
                            City = "Austin",
                            EmployeeId = 2,
                            State = "TX",
                            Zip = "73301"
                        },
                        new
                        {
                            Id = 3,
                            Address1 = "789 Pine Rd",
                            Address2 = "Suite 200",
                            City = "Denver",
                            EmployeeId = 3,
                            State = "CO",
                            Zip = "80202"
                        },
                        new
                        {
                            Id = 4,
                            Address1 = "321 Maple Dr",
                            City = "Seattle",
                            EmployeeId = 4,
                            State = "WA",
                            Zip = "98101"
                        },
                        new
                        {
                            Id = 5,
                            Address1 = "654 Elm St",
                            City = "Raleigh",
                            EmployeeId = 5,
                            State = "NC",
                            Zip = "27601"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Server.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 34,
                            Email = "jane.doe@example.com",
                            FirstName = "Jane",
                            LastName = "Doe",
                            PhoneNumber = "(555)-123-4567"
                        },
                        new
                        {
                            Id = 2,
                            Age = 45,
                            Email = "john.smith@example.com",
                            FirstName = "John",
                            LastName = "Smith",
                            PhoneNumber = "(555)-234-5678"
                        },
                        new
                        {
                            Id = 3,
                            Age = 29,
                            Email = "maria.garcia@example.com",
                            FirstName = "Maria",
                            LastName = "Garcia",
                            PhoneNumber = "(555)-345-6789"
                        },
                        new
                        {
                            Id = 4,
                            Age = 52,
                            Email = "david.lee@example.com",
                            FirstName = "David",
                            LastName = "Lee",
                            PhoneNumber = "(555)-456-7890"
                        },
                        new
                        {
                            Id = 5,
                            Age = 38,
                            Email = "aisha.khan@example.com",
                            FirstName = "Aisha",
                            LastName = "Khan",
                            PhoneNumber = "(555)-567-8901"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Server.Data.Address", b =>
                {
                    b.HasOne("EmployeeManagement.Server.Data.Employee", "Employee")
                        .WithOne("Address")
                        .HasForeignKey("EmployeeManagement.Server.Data.Address", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeManagement.Server.Data.Employee", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
